import { useState, useEffect } from "react";
import { Printer, FileText } from "lucide-react";
import purchaseOrderService from "../../services/purchaseOrderService";
import "./ReportsSection.css";

export const ReportsSection = () => {
  const [purchaseOrders, setPurchaseOrders] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadReports();
  }, []);

  const loadReports = async () => {
    setLoading(true);
    try {
      const pos = await purchaseOrderService.getAll();
      setPurchaseOrders(pos || []);
    } catch (error) {
      console.error("Failed to load reports", error);
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  const getStatusClass = (status) => {
    if (!status) return 'status-default';
    const s = status.toLowerCase();
    if (s.includes('pending')) return 'status-pending';
    if (s.includes('approve')) return 'status-approved';
    if (s.includes('reject')) return 'status-rejected';
    if (s.includes('deliver')) return 'status-delivered';
    return 'status-default';
  };

  // Calculate summaries
  const totalSpend = purchaseOrders.reduce((sum, po) => sum + (po.totalAmount || 0), 0);
  const approvedSpend = purchaseOrders
    .filter(po => po.status === 'APPROVED' || po.status === 'DELIVERED')
    .reduce((sum, po) => sum + (po.totalAmount || 0), 0);
  const pendingSpend = purchaseOrders
    .filter(po => po.status === 'PENDING')
    .reduce((sum, po) => sum + (po.totalAmount || 0), 0);

  if (loading) {
    return <div className="loading-state">Generating reports...</div>;
  }

  return (
    <div className="reports-section animate-fade-in">
      <div className="reports-header">
        <div>
          <h2>Financial Reports</h2>
          <p>Audit and track all system purchase orders and spending.</p>
        </div>
      </div>

      <div className="summary-cards">
        <div className="summary-card total">
          <div className="summary-title">Total PO Volume</div>
          <div className="summary-value">
            ${totalSpend.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </div>
        </div>
        <div className="summary-card approved">
          <div className="summary-title">Approved Spend</div>
          <div className="summary-value">
            ${approvedSpend.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </div>
        </div>
        <div className="summary-card pending">
          <div className="summary-title">Pending Spend</div>
          <div className="summary-value">
            ${pendingSpend.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </div>
        </div>
      </div>

      <div className="report-table-container">
        <div className="report-toolbar">
          <div className="report-title">
            <FileText size={18} color="#3b82f6" />
            Master Purchase Order Log
          </div>
          <button className="btn-print" onClick={handlePrint}>
            <Printer size={16} />
            Print / Save as PDF
          </button>
        </div>

        {purchaseOrders.length === 0 ? (
          <div className="empty-state">No purchase orders available for reporting.</div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>Date</th>
                <th>PO Number</th>
                <th>Supplier</th>
                <th>Generated By</th>
                <th>Status</th>
                <th>Amount</th>
              </tr>
            </thead>
            <tbody>
              {purchaseOrders.map((po) => (
                <tr key={po.id}>
                  <td>{po.createdAt ? new Date(po.createdAt).toLocaleDateString() : 'N/A'}</td>
                  <td style={{ fontWeight: 500, color: '#3b82f6' }}>{po.poNumber}</td>
                  <td>{po.supplierName || 'Unknown Supplier'}</td>
                  <td>{po.generatedByName || 'System'}</td>
                  <td>
                    <span className={`status-badge ${getStatusClass(po.status)}`}>
                      {po.status || 'UNKNOWN'}
                    </span>
                  </td>
                  <td style={{ fontWeight: 600, color: '#0f172a' }}>
                    ${(po.totalAmount || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
};
