package com.eps.enterprise_procurement_system.controllers;

import java.util.List;

import com.eps.enterprise_procurement_system.dto.PurchaseOrderHistoryResponseDTO;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import com.eps.enterprise_procurement_system.advices.ApiResponse;
import com.eps.enterprise_procurement_system.dto.PurchaseOrderRequestDTO;
import com.eps.enterprise_procurement_system.dto.PurchaseOrderResponseDTO;
import com.eps.enterprise_procurement_system.dto.PurchaseOrderStatusRequestDTO;
import com.eps.enterprise_procurement_system.entities.enums.PurchaseOrderStatus;
import com.eps.enterprise_procurement_system.services.PurchaseOrderService;
import com.eps.enterprise_procurement_system.util.CurrentUser;

import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;

@RestController
@RequestMapping("/purchase-orders")
@RequiredArgsConstructor
public class PurchaseOrderController {

    private final PurchaseOrderService purchaseOrderService;
    private final CurrentUser currentUser;

    // ======================================================
    // Generate Purchase Order
    // ======================================================

    @PostMapping
    @PreAuthorize("hasAnyRole('PROCUREMENT','ADMIN')")
    public ResponseEntity<ApiResponse<PurchaseOrderResponseDTO>> generatePurchaseOrder(@Valid @RequestBody PurchaseOrderRequestDTO dto) {

        return ResponseEntity.ok(new ApiResponse<>(purchaseOrderService.generatePurchaseOrder(
                dto,
                currentUser.get())));
    }

    // Get All Purchase Orders

    @GetMapping
    @PreAuthorize("hasAnyRole('ADMIN','PROCUREMENT','FINANCE','MANAGER')")
    public ResponseEntity<ApiResponse<List<PurchaseOrderResponseDTO>>> getAllPurchaseOrders() {

        return ResponseEntity.ok(new ApiResponse<>(purchaseOrderService.getAllPurchaseOrders()));
    }




    // Get Purchase Order By Id

    @GetMapping("/{id}")
    @PreAuthorize("hasAnyRole('ADMIN','PROCUREMENT','FINANCE','MANAGER')")
    public ResponseEntity<ApiResponse<PurchaseOrderResponseDTO>> getPurchaseOrder(
            @PathVariable Long id) {

        return ResponseEntity.ok(new ApiResponse<>(purchaseOrderService.getPurchaseOrderById(id)));
    }

//    @GetMapping("/{requisitionId}/requisition")
//    @PreAuthorize("hasAnyRole('ADMIN','PROCUREMENT','FINANCE','MANAGER')")
//    public ResponseEntity<ApiResponse<PurchaseOrderResponseDTO>> getPurchaseOrderByRequisionId(
//            @PathVariable Long requisitionId) {
//
//        return ResponseEntity.ok(new ApiResponse<>(purchaseOrderService.getPurchaseOrderByRequisitionId(requisitionId)));
//    }

    // Get Purchase Orders By Status

    @GetMapping("/status/{status}")
    @PreAuthorize("hasAnyRole('ADMIN','PROCUREMENT','FINANCE','MANAGER')")
    public ResponseEntity<ApiResponse<List<PurchaseOrderResponseDTO>>> getByStatus(@PathVariable PurchaseOrderStatus status) {

        return ResponseEntity.ok(new ApiResponse<>(purchaseOrderService.getPurchaseOrdersByStatus(status)));
    }

    // Get Orders of Supplier

    @GetMapping("/supplier/{supplierId}")
    @PreAuthorize("hasAnyRole('ADMIN','PROCUREMENT','FINANCE')")
    public ResponseEntity<ApiResponse<List<PurchaseOrderResponseDTO>>> getSupplierOrders(@PathVariable Long supplierId) {

        return ResponseEntity.ok(new ApiResponse<>(purchaseOrderService.getSupplierOrders(supplierId)));
    }

    // Orders Generated By Logged Procurement Officer

    @GetMapping("/my-orders")
    @PreAuthorize("hasRole('PROCUREMENT')")
    public ResponseEntity<ApiResponse<List<PurchaseOrderResponseDTO>>> myOrders() {

        return ResponseEntity.ok(new ApiResponse<>(purchaseOrderService.getGeneratedOrders(currentUser.get().getId())));
    }

//    @GetMapping("{poId}/history")
//    public ResponseEntity<ApiResponse<List<PurchaseOrderHistoryResponseDTO>>> getHistory(@PathVariable Long poId){
//
//        return ResponseEntity.ok(new ApiResponse<>(purchaseOrderService.getHistory(poId)));
//    }
//    // Update Status

    @PutMapping("/{id}/status")
    @PreAuthorize("hasAnyRole('PROCUREMENT','ADMIN')")
    public ResponseEntity<ApiResponse<PurchaseOrderResponseDTO>> updateStatus(
            @PathVariable Long id,
            @Valid @RequestBody PurchaseOrderStatusRequestDTO dto) {

        return ResponseEntity.ok(new ApiResponse<>(purchaseOrderService.updateStatus(
                id,
                dto.getStatus(),
                currentUser.get())));
    }

    // ======================================================
    // Cancel Purchase Order
    // ======================================================

    @PutMapping("/{id}/cancel")
    @PreAuthorize("hasAnyRole('PROCUREMENT','ADMIN')")
    public String cancelPurchaseOrder(@PathVariable Long id) {

        return purchaseOrderService.cancelPurchaseOrder(id, currentUser.get());

    }

    // Delete Purchase Order (Optional)

    @DeleteMapping("/{id}")
    @PreAuthorize("hasRole('ADMIN')")
    public String deletePurchaseOrder(@PathVariable Long id) {

        return purchaseOrderService.deletePurchaseOrder(id);
    }

    // Download Purchase Order PDF

    @GetMapping("/{id}/pdf")
    @PreAuthorize("hasAnyRole('ADMIN','PROCUREMENT','FINANCE','MANAGER')")
    public ResponseEntity<byte[]> downloadPurchaseOrderPdf(@PathVariable Long id) {

        byte[] pdf = purchaseOrderService.generatePurchaseOrderPdf(id);

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION,
                    "attachment; filename=PurchaseOrder_" + id + ".pdf")
                .contentType(MediaType.APPLICATION_PDF)
                .body(pdf);
    }

    // Download Invoice PDF

    @GetMapping("/{id}/invoice")
    @PreAuthorize("hasAnyRole('ADMIN','PROCUREMENT','FINANCE')")
    public ResponseEntity<byte[]> downloadInvoice(@PathVariable Long id) {

        byte[] pdf = purchaseOrderService.generateInvoice(id);

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        "attachment; filename=Invoice_" + id + ".pdf")
                .contentType(MediaType.APPLICATION_PDF)
                .body(pdf);
    }

    // Download Goods Receipt PDF

    // @GetMapping("/{id}/grn")
    // @PreAuthorize("hasAnyRole('ADMIN','PROCUREMENT','WAREHOUSE')")
    // public ResponseEntity<byte[]> downloadGRN(@PathVariable Long id) {

    //     byte[] pdf = purchaseOrderService.receiveGoodsReceipt(id);

    //     return ResponseEntity.ok()
    //             .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=GRN_" + id + ".pdf")
    //             .contentType(MediaType.APPLICATION_PDF)
    //             .body(pdf);
    // }

    // Export All Purchase Orders Excel

    @GetMapping("/export")
    @PreAuthorize("hasAnyRole('ADMIN','PROCUREMENT','FINANCE')")
    public ResponseEntity<byte[]> exportPurchaseOrders() {

        byte[] excel = purchaseOrderService.exportPurchaseOrders();

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        "attachment; filename=PurchaseOrders.xlsx")
                .contentType(MediaType.APPLICATION_OCTET_STREAM)
                .body(excel);
    }

    // Export Purchase Orders By Status

    @GetMapping("/export/status/{status}")
    @PreAuthorize("hasAnyRole('ADMIN','PROCUREMENT','FINANCE')")
    public ResponseEntity<byte[]> exportByStatus(
            @PathVariable PurchaseOrderStatus status) {

        byte[] excel =
                purchaseOrderService.exportPurchaseOrdersByStatus(status);

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        "attachment; filename=PurchaseOrders_" + status + ".xlsx")
                .contentType(MediaType.APPLICATION_OCTET_STREAM)
                .body(excel);
    }

    // Export Supplier Purchase Orders

    @GetMapping("/export/supplier/{supplierId}")
    @PreAuthorize("hasAnyRole('ADMIN','PROCUREMENT','FINANCE')")
    public ResponseEntity<byte[]> exportSupplierOrders(@PathVariable Long supplierId) {

        byte[] excel = purchaseOrderService.exportSupplierOrders(supplierId);

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION,
                        "attachment; filename=SupplierOrders.xlsx")
                .contentType(MediaType.APPLICATION_OCTET_STREAM)
                .body(excel);
    }

}