package com.eps.enterprise_procurement_system.entities.enums;

public enum RequisitionStatus {
    DRAFT,
    SUBMITTED,
    PARTIALLY_ORDERED,
    DUPLICATE_FLAGGED,
    PENDING_MANAGER,
    MANAGER_REJECTED,
    PENDING_FINANCE,
    FINANCE_REJECTED,
    PENDING_ADMIN,
    PENDING_PROCUREMENT,
    PROCUREMENT_REJECTED,
    ADMIN_REJECTED,
    APPROVED,
    SOURCING,
    PO_GENERATED,
    CANCELLED
}