package com.eps.enterprise_procurement_system.services;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.List;

import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import com.eps.enterprise_procurement_system.entities.PoItem;
import com.eps.enterprise_procurement_system.entities.PurchaseOrder;

@Service
public class ExcelService {

    public byte[] exportPurchaseOrders(List<PurchaseOrder> orders) {
        try (XSSFWorkbook workbook = new XSSFWorkbook()) {

            XSSFSheet sheet = workbook.createSheet("Purchase Orders");

            Row header = sheet.createRow(0);

            header.createCell(0).setCellValue("PO Number");
            header.createCell(1).setCellValue("Requisition");
            header.createCell(2).setCellValue("Supplier");
            header.createCell(3).setCellValue("Generated By");
            header.createCell(4).setCellValue("Status");
            header.createCell(5).setCellValue("Amount");
            header.createCell(6).setCellValue("Expected Delivery");
            header.createCell(7).setCellValue("Created At");

            int rowNum = 1;

            for (PurchaseOrder po : orders) {

                Row row = sheet.createRow(rowNum++);

                row.createCell(0).setCellValue(po.getPoNumber());

                row.createCell(1).setCellValue(po.getRequisition().getRequisitionNo());

                row.createCell(2).setCellValue(po.getSupplier().getUser().getFullName());

                row.createCell(3).setCellValue(po.getGeneratedBy().getFullName());

                row.createCell(4).setCellValue(po.getStatus().name());

                row.createCell(5).setCellValue(po.getTotalAmount().doubleValue());

                row.createCell(6).setCellValue(po.getExpectedDeliveryDate().toString());

                row.createCell(7).setCellValue(po.getCreatedAt().toString());
            }

            for (int i = 0; i < 8; i++) {
                sheet.autoSizeColumn(i);
            }

            ByteArrayOutputStream output = new ByteArrayOutputStream();

            workbook.write(output);

            return output.toByteArray();

        }

        catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public byte[] exportPOItems(PurchaseOrder order) {

        try (XSSFWorkbook workbook = new XSSFWorkbook();
            
                ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            XSSFSheet sheet = workbook.createSheet("Purchase Order Items");

            int rowNum = 0;

            // Header
            Row header = sheet.createRow(rowNum++);

            header.createCell(0).setCellValue("PO Number");
            header.createCell(1).setCellValue("Product");
            header.createCell(2).setCellValue("SKU");
            header.createCell(3).setCellValue("Quantity");
            header.createCell(4).setCellValue("Unit Price");
            header.createCell(5).setCellValue("Total");

            // Data
            for (PoItem item : order.getPoItems()) {

                Row row = sheet.createRow(rowNum++);

                row.createCell(0).setCellValue(order.getPoNumber());

                row.createCell(1).setCellValue(item.getProduct().getName());

                row.createCell(2).setCellValue(item.getProduct().getSku());

                row.createCell(3).setCellValue(item.getQuantity());

                row.createCell(4).setCellValue(item.getUnitPrice().doubleValue());

                row.createCell(5).setCellValue(item.getUnitPrice()
                        .multiply(java.math.BigDecimal.valueOf(item.getQuantity()))
                        .doubleValue());
            }

            // Auto Size Columns
            for (int i = 0; i <= 5; i++) {
                sheet.autoSizeColumn(i);
            }

            workbook.write(out);

            return out.toByteArray();

        } 
        catch (IOException e) {
            throw new RuntimeException("Unable to export PO Items", e);
        }
    }
}
